### ISSUE TITLE
TypeError: login() takes exactly 4 arguments (3 given)

### ISSUE THREAD

**Issue by xbeta** [rraval/rdio-gmusic#3]
``` bash
Create an App Specific Password to use with your Google Account
See https://support.google.com/accounts/answer/185833

mygmail@gmail.com Password:

Traceback (most recent call last):
  File "/usr/local/bin/rdio-gmusic", line 9, in <module>
    load_entry_point('rdio-gmusic==0.1', 'console_scripts', 'rdio-gmusic')()
  File "/Library/Python/2.7/site-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rdio_gmusic.py", line 170, in main
    gmusic = GMusic(google_user, google_password)
  File "/Library/Python/2.7/site-packages/rdio_gmusic.py", line 96, in __init__
    self.client.login(user, password)
TypeError: login() takes exactly 4 arguments (3 given)
```

**Comment by rraval** [comment]
#2 fixes this specific issue but #1 still prevents the script from functioning. I'll free up some time and get a new release out on pip.

**Comment by xbeta** [comment]
@rraval thanks! since Rdio is now going to be gone, I can't wait to transfer everything to Google Music before the shutdown.

**Comment by jgillich** [comment]
Oh so this doesn't actually work, that's unfortunate.
