### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by steadystatic** [rraval/rdio-gmusic#4]
I just cloned latest from the repo, ran `python setup.py install` and tried.

Am getting this output:

Existing Google Music  [####################################]  56
Rdio -> Google Music  [------------------------------------]  0
Traceback (most recent call last):
  File "/usr/local/bin/rdio-gmusic", line 9, in <module>
    load_entry_point('rdio-gmusic==0.1', 'console_scripts', 'rdio-gmusic')()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 700, in **call**
    return self.main(_args, *_kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, *_ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(_args, **kwargs)
  File "build/bdist.macosx-10.10-x86_64/egg/rdio_gmusic.py", line 191, in main
    for track in bar:
  File "/usr/local/lib/python2.7/site-packages/click/_termui_impl.py", line 240, in next
    rv = next(self.iter)
  File "build/bdist.macosx-10.10-x86_64/egg/rdio_gmusic.py", line 72, in genTracks
    'vanityName': user,
  File "build/bdist.macosx-10.10-x86_64/egg/rdio_gmusic.py", line 67, in request
    return json.loads(response[1])['result']
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by blavoie** [comment]
Same thing here.
